version: "3.7"

services:
    api_legal_render:
        container_name: api_legal_render
        build:
            context: .
            dockerfile: Dockerfile
        image: api_exemplo_render
        ports:
            - "8075:8080"